[package]
name = "pdf_metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
lopdf = "0.36.0" # Ou a versão mais recente disponível
chrono = { version = "0.4", features = ["wasm-bindgen"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
dialoguer = "0.11"
atty = "0.2"